name: Fetching github repo on github runner
on: [push]

jobs:
    checkout-files-and-display-files:
        runs-on: ubuntu-latest
        steps:
            - name: List Files Before
              run: ls -a
            - name: perform Checkout
              run: |
               git init
               git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
               git fetch origin
               git checkout main
            - name: List Files Before
              run: ls -a
    checkout-files-using-actions:
                runs-on: ubuntu-latest
                steps:
                    - name: List Files Before
                      run: ls -a
                    - uses: actions/checkout@v4
                    - name: List Files Before
                      run: ls -a