name: First Workflow
on: [push]

jobs: 
    run-shell-commands:
        runs-on: ubuntu-latest
        steps:
            - name: echo a string
              run: echo "Invoking First Github Actions"
            
            - name: Multiline Commands
              run: |
                node -v
                npm -v
    parallel-job-macos:
        runs-on: macos-latest
        steps:
            - name: View SW version
              run: sw_vers
    dependent-job:
        runs-on: windows-latest
        needs: run-shell-commands
        steps:
            - name: echo some string
              run: doestexists 
              
