name: Woring Dirs & Shells
on: [push]

jobs:
    Exploring_Working_Dirs:
        runs-on: ubuntu-latest
        steps:
            - name : explore working directory
              run: |
                pwd
                ls -lt
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE
            - name: changing working directory
              working-directory: /home/runner/work/GitActions/
              run: pwd 
    
    Exploring_Working_Dirs_Windows:
            runs-on: windows-latest
            # defaults:
            #     run:
            #       shell: powershell
            steps:
                - name : explore working directory for windows
                  run: |
                    Get-Location
                    dir
                    echo $env:GITHUB_SHA
                    echo $env:GITHUB_REPOSITORY
                    echo $env:GITHUB_WORKSPACE 
